### ISSUE TITLE
Coordinator exits on RecvError/Connection close

### ISSUE THREAD

**Issue by f321x** [f321x/cashu-escrow-kit#11]
As the coordinator should be a long running application maybe we could also try to reinitialize the coordinator (close all connection/subscriptions and set them up again) on error, and check if the error doesn't happen again in a specified timeframe (e.g. 30 mins), so it would be more reliable and not crash if there is a cause (e.g. short internet outage) that closes the relay pool from time to time.

**Comment by rodant** [comment]
Implemented.
