### ISSUE TITLE
Logging and debugging concept needed

### ISSUE THREAD

**Issue by rodant** [f321x/cashu-escrow-kit#13]
We need a general concept for debugging or logging at different levels: error, warning, info, etc. Let's find a good solution for that and implement it across the project.

**Comment by f321x** [comment]
I previously used the [env_logger crate](https://docs.rs/env_logger/latest/env_logger) for this use case. 
It can be initialized like this:
```rust
fn main() -> Result<()> {
	env_logger::builder()
		.filter_module("trader", log::LevelFilter::Debug)
		.filter_level(log::LevelFilter::Info)
		.init();
```
then we have the following macros available for logging:
```rust
error!()
warn!()
info!()
debug()!
trace!()
```

**Comment by f321x** [comment]
Fixed with https://github.com/f321x/cashu-escrow-kit/pull/19
